import logging 
import os 
#agent_log.text that is if we will like to name it that way , it could be anything 
agent_name = os.path.join(os.getcwd(), 'agent_log.txt')
logging.basicConfig(filename=agent_name, 
                    level=logging.INFO, format= '%(asctime)s - %(levelname)s - %(message)s')

def log_agent_interaction(agent_input, agent_output):
    """
    Logs the agent's input and output to a file.

    Parameters:
    agent_input (str): The input provided to the agent.
    agent_output (str): The output generated by the agent.
    """
    logging.info(f'Input: {agent_input}')
    logging.info(f'Output: {agent_output}')



    

