import os
import click
import shutil
import requests
from benchtools.runner import Bench
# from task import PromptTask

@click.group()
def cli():
    """
    BenchTools is a tool that helps researchers set up benchmarks.
    """
    pass


## AS: Come back to this soon
@click.command()
@click.argument('bench_name')
def generate_demo_bench(bench_name):
    """
    Generate a demo benchmark
    """

    # Set up directory for the demo bench
    current_dir = os.getcwd()
    parent_dir = os.path.abspath(os.path.join(current_dir, ".."))
    # Change this to use the current path or possibly take a path as an argument
    demo_bench_path = os.path.join(parent_dir, bench_name)
    os.makedirs(demo_bench_path, exist_ok=True)

    tasks_folder = os.path.join(demo_bench_path, "Tasks")
    report_folder = os.path.join(demo_bench_path, "Report")

    os.makedirs(tasks_folder, exist_ok=True)
    os.makedirs(report_folder, exist_ok=True)

    click.echo(f"Folder '{bench_name}' created at {demo_bench_path}")
    click.echo("Subfolders 'Tasks' and 'Report' created.")


## Sub-functions for the init method

### If user calls init without a benchmark name as an argument
def get_benchmark_name():
    return input("Enter the name of your benchmark/project (will be used as folder and repo name)...\n")


### Generate an about path from the description of the user 
def create_about(bench_name, bench_path, text):
    about_path = os.path.join(bench_path, bench_name, "about.md")
    about_text= f"""
    # {bench_name}
    {text}

    Generated by BenchTools
    """
    with open(about_path, 'w') as file:
        file.write(about_text)


### Initialize git repository
def init_repo(bench_name, bench_path):
    current_dir = os.getcwd()
    benchmark_path = os.path.join(bench_path, bench_name)
    os.chdir(benchmark_path)
    try:
        os.system("git init . -q")
        os.system("git branch -m main")
    except:
        print("git might not be initialized in your system. Please run \"git init . \" when setup")
    # Get python gitignore template and create .gitignore
    ignore_text = requests.get("https://raw.githubusercontent.com/github/gitignore/refs/heads/main/Python.gitignore")
    if ignore_text.status_code == 200:
        with open(".gitignore", 'a') as f:
            f.write(ignore_text.text)
    os.chdir(current_dir)


# Create a benchmarks folder with tasks in them
def setup_task(tasks_path, task_name, task_path):

    click.echo(f"Setting up {task_name}...", nl=False)
    task_folder = os.path.join(tasks_path, task_name)
    os.mkdir(task_folder) # TODO: check if folder exists and handle

    # Path could be absolute or relative, check and work accordingly
    if not task_path.startswith('/'):
        if task_path.startswith('./'):
            # TODO: Path could have one or more `../` use relpath to fix this block 
            task_path = task_path[2:]
        task_path = os.path.join(os.getcwd(), task_path)
        # print(f" path {task_path}\n\n") # Debugging
    
    #  could be a single file or a folder check and work accordignly
    if os.path.isdir(task_path):
        for sub in os.listdir(task_path):
            shutil.copy2(os.path.join(task_path, sub), task_folder)
    else:
        shutil.copy2(task_path, task_folder)
    click.echo("Success")


# Initialize the benchmark 
@click.command()
@click.argument('benchmark_name', required=False)
@click.option('--path', '-p', default=".", help="The path where the benchmark repository will be")
@click.option('--about', '-a', default="", help="The Content that goes in the about.md file")
@click.option('--no-git', is_flag=True, help="Don't make benchmark a git repository. Default is False")
@click.option('--tasks', '-t', type=(str, str), multiple=True, default=[], help="Add benchmark tasks to your benchmark <name> <path>")
def init(benchmark_name, path, about, no_git, tasks):
    """Initializing a new benchmark."""
    # new_benchmark = PromptTask()
    if not benchmark_name:
        benchmark_name = get_benchmark_name()
    click.echo("Creating " + benchmark_name + " in " + path)
    
    # Create the benchmark folder
    bench_path = os.path.join(path, benchmark_name)
    os.mkdir(bench_path)

    # Initialize a git repo
    if not no_git:
        init_repo(benchmark_name, path) # TODO: bench_path?
    
    # Create about.md
    create_about(benchmark_name, path, about) # TODO: bench_path?

    # Create a benchmarks folder with tasks in them
    tasks_path = os.path.join(bench_path, "benchmarks")
    os.mkdir(tasks_path)
    for task_name, task_path in tasks:
        setup_task(tasks_path, task_name, task_path)

    to_run = input(" Would you like to run the benchmark? y/n? ")
    print()
    if to_run in ['y', 'Y', 'yes', "YES", 'Yes', 'yyes']:
        benchmark = Bench(bench_path, "something")


# What us creating a new task
@click.command()
@click.argument('task_name', required = True)
# @click.option()
def add_task(task_name):
    """Setting up a new task."""
    # new_task = PromptTask()
    click.echo("Adding " + task_name)
    

@click.command()
@click.argument('benchmark',type=str, required = True)
def run(benchmark: str):
    """Running the benchmark and generating logs"""
    bench_path = os.path.join(os.getcwd(), benchmark)
    
    # TODO: Fix relPath case
    click.echo(f"Running {benchmark.rsplit('/',maxsplit=1)[1]} now")
    benchmark = Bench(benchmark, "something")

@click.command()
@click.argument('task_name', required = True)
def run_task(task_name):
    """Running the tasks and generating logs"""
    
    click.echo(f"Running {task_name} now")


cli.add_command(init)
cli.add_command(run)
cli.add_command(add_task)
cli.add_command(run_task)
cli.add_command(generate_demo_bench)


if __name__ == "__main__":
    cli()
