import os
import click
# from task import PromptTask
# from runner import Bench

@click.group()
def cli():
    """
    BenchTools is a tool that helps researchers set up benchmarks.
    """
    pass


## AS: Come back to this soon
@click.command()
@click.argument('bench_name')
def generate_demo_bench(bench_name):
    """
    Generate a demo benchmark
    """

    # Set up directory for the demo bench
    current_dir = os.getcwd()
    parent_dir = os.path.abspath(os.path.join(current_dir, ".."))
    # Change this to use the current path or possibly take a path as an argument
    demo_bench_path = os.path.join(parent_dir, bench_name)
    os.makedirs(demo_bench_path, exist_ok=True)

    tasks_folder = os.path.join(demo_bench_path, "Tasks")
    report_folder = os.path.join(demo_bench_path, "Report")

    os.makedirs(tasks_folder, exist_ok=True)
    os.makedirs(report_folder, exist_ok=True)

    click.echo(f"Folder '{bench_name}' created at {demo_bench_path}")
    click.echo("Subfolders 'Tasks' and 'Report' created.")


## Sub-functions for the init method

### If user calls init without a benchmark name as an argument
def get_benchmark_name():
    return input("Enter the name of your benchmark/project (will be used as folder and repo name)...\n")


### Generate an about path from the description of the user 
def create_about(bench_name, bench_path, text):
    about_path = os.path.join(bench_path, bench_name, "about.md")
    about_text= f"""
    # {bench_name}
    {text}

    Generated by BenchTools
    """
    with open(about_path, 'w') as file:
        file.write(about_text)

    
    

# Initialize the benchmark 
@click.command()
@click.argument('benchmark_name', required = False)
@click.option('--path', '-P', default=".", help="The path where the benchmark repository will be")
@click.option('--about', '-A', default="", help="The Content that goes in the about.md file")
def init(benchmark_name, path, about):
    """Initializing a new benchmark."""
    # new_benchmark = PromptTask()
    if not benchmark_name:
        benchmark_name = get_benchmark_name()
    click.echo("Creating " + benchmark_name + " in " + path)
    os.mkdir(os.path.join(path, benchmark_name))
    create_about(benchmark_name, path, about)



# What us creating a new task
@click.command()
@click.argument('task_name')
def add_task(task_name):
    """Creating a new task."""
    new_task = PromptTask()
    click.echo("Adding " + task_name)


@click.command()
@click.argument('task_name')
def run_task(task_name):
    """Running a task."""
    
    click.echo(result)


cli.add_command(init)
cli.add_command(add_task)
cli.add_command(run_task)
cli.add_command(generate_demo_bench)


if __name__ == "__main__":
    cli()
