import os 
import logging 

log_folder: str

def init_logger(log_path, task_name):
    log_file = os.path.join(log_path, f'{task_name}_log.txt')
    logging.basicConfig(filename=log_file, 
                    level=logging.INFO, format= '%(asctime)s - %(levelname)s - %(message)s')

def log_agent_interaction(agent_input, agent_output):
    """
    Logs the agent's input and output to a file.

    Parameters:
    agent_input (str): The input provided to the agent.
    agent_output (str): The output generated by the agent.
    """
    logging.info(f'Input: {agent_input}')
    logging.info(f'Output: {agent_output}')



    

