import os
import logging 
import datetime

def init_logger(log_path, model, task_name):
    ''''
    Initializes the logger for a specific task.
    
    Parameters:
    -------------
    log_path: str
        The path to the log dir where the log file will be created.
    model: 
        The name of the model running the task
    task_name: str
        The name of the task for which the logger is being initialized. This will be used to name the log file.
    '''
    # Get timestamp without fractions of seconds
    timestamp = int(datetime.datetime().now().timestamp())

    model_dir = os.path.join(log_path, model)
    if not os.path.exists(model_dir):
        os.mkdir(model_dir)

    task_dir = os.path.join(model_dir, task_name)
    if not os.path.exists(task_dir):
        os.mkdir(task_dir)

    run_dir = os.path.join(task_dir, str(timestamp))
    os.mkdir(run_dir)

    {
        # TODO: What can we benifit from the logger?
        # log_file = os.path.join(log_path, f'{task_name}_log.txt')
        # print(f"\nLOGPATH: {log_file}\n") # Debugging

        # formatter = logging.Formatter('%(asctime)s - %(levelname)s - %(message)s')
        # handler = logging.FileHandler(log_file)
        # handler.setFormatter(formatter)

        # logger = logging.getLogger(task_name)
        # logger.setLevel(logging.INFO) # TODO add as an argument to the init functuion to use more options 
        # logger.addHandler(handler)

        # print(logger) # Debugging
        # return logger
    }

    return run_dir

def log_interaction(run_log_path, prompt_idx, prompt, response):
    """
    Logs the event to the log folder specified by the user

    Parameters:
    -------------
    run_log_path: str
        Path to a run-specific directory in a log directory specified in a call to the run method
    prompt_idx: str
        Index of the sub-task being logged
    prompt: string
        The input provided to the model.
    response: string
        The output generated by the model.
    """

    prompt_dir = os.path.join(run_log_path, f"prompt_{prompt_idx}")
    os.mkdir(prompt_dir)

    with open(os.path.join(prompt_dir, "log.txt"), 'w') as f:
        f.write("------ prompt ------\n")
        f.write(f"{prompt}\n\n")
        f.write("------ response ------\n")
        f.write(f"{response}\n\n")

    # TODO: What can we benifit from the logger?
    # logger.info(f'Input: {prompt}')
    # logger.info(f'Output: {response}')



    

