import os 
import logging 

def init_logger(log_path, task_name):
    ''''
    Initializes the logger for a specific task.
    
    Parameters:
    -------------
    log_path: str
        The path to the log folder where the log file will be created.
    task_name: str
        The name of the task for which the logger is being initialized. This will be used to name the log file.
    '''
    log_file = os.path.join(log_path, f'{task_name}_log.txt')
    # print(f"\nLOGPATH: {log_file}\n") # Debugging

    formatter = logging.Formatter('%(asctime)s - %(levelname)s - %(message)s')
    handler = logging.FileHandler(log_file)
    handler.setFormatter(formatter)

    logger = logging.getLogger(task_name)
    logger.setLevel(logging.INFO) # TODO add as an argument to the init functuion to use more options 
    logger.addHandler(handler)

    # print(logger) # Debugging
    return logger

def log_agent_interaction(logger, agent_input, agent_output):
    """
    Logs the agent's input and output to a file.

    Parameters:
    -------------
    agent_input: string
        The input provided to the agent.
    agent_output: string
        The output generated by the agent.
    """
    logger.info(f'Input: {agent_input}')
    logger.info(f'Output: {agent_output}')



    

